include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  errors:
    avoid_print: ignore
    annotate_overrides: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '_flutter'
