name: nererun
description: A new Flutter project.
publish_to: 'none'
version: 2022.12.2+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.1

  assets_audio_player: ^3.0.5
  simple_logger: ^1.9.0+1
  url_launcher: ^6.1.7
  package_info: ^2.0.2
  app_review: ^2.1.1+1
  freezed_annotation: ^2.1.0
  riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  purchases_flutter: ^3.2.2

  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.5
  firebase_messaging: ^11.2.3
  flutter_local_notifications: ^9.1.5
  firebase_crashlytics: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner:
  json_serializable:
  freezed: ^2.1.1

flutter_icons:
  android: true 
  ios: true
  image_path: "icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: NotoSansJpBold
      fonts:
        - asset: fonts/NotoSansJP-Bold.otf
    - family: NotoSansJpRegular
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
