# vim: syntax=ruby

default_platform(:ios)

platform :ios do
  lane :certificates do
    setup_ci(provider: 'travis')

    username = 'tomokisun'
    personal_github_access_token = ENV['PERSONAL_ACCESS_TOKEN']
    authorization_token_str = "#{username}:#{personal_github_access_token}"
    basic_authorization_token = Base64.strict_encode64(authorization_token_str)

    match(
      type: 'appstore',
      git_basic_authorization: basic_authorization_token,
      app_identifier: ['tokyo.gajo.app.ios.nererun'],
    )
  end
end
