name: push

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/workflows/scripts/install-flutter.sh 3.16.4
      - run: ./.github/workflows/scripts/install-tools.sh
      - run: flutter pub get
      - run: flutter analyze
  codegen:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./.github/workflows/scripts/install-flutter.sh 3.16.4
    - run: ./.github/workflows/scripts/install-tools.sh
    - run: flutter pub get
    - run: make generate
    - run: git diff --quiet --exit-code
