name: main

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare firebase config
        run: |
          echo $FILE_FIREBASE_IOS_DEVELOPMENT | base64 -D > ios/Runner/GoogleService-Info-debug.plist
          echo $FILE_FIREBASE_IOS_PRODUCTION | base64 -D > ios/Runner/GoogleService-Info-release.plist
        env:
          FILE_FIREBASE_IOS_DEVELOPMENT: ${{ secrets.FILE_FIREBASE_IOS_DEVELOPMENT }}
          FILE_FIREBASE_IOS_PRODUCTION: ${{ secrets.FILE_FIREBASE_IOS_PRODUCTION }}
      - run: ./.github/workflows/scripts/install-flutter.sh 3.16.4
      - run: ./.github/workflows/scripts/install-tools.sh
      - run: flutter pub get
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - run: bundle install --path vendor/bundle --jobs 4 --retry 3
        working-directory: ios
      - run: bundle exec fastlane certificates
        working-directory: ios
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - run: flutter build ipa --dart-define=FLAVOR=Production --release --export-options-plist=./ios/ExportOptions/release.plist --build-name $(date '+%Y').$(date '+%m').$(date '+%d') --build-number ${GITHUB_RUN_ID}
      - run: xcrun altool --upload-app -t ios -f ./build/ios/ipa/nererun.ipa -u "${{ secrets.APPLE_ID }}" -p "${{ secrets.APPLE_APP_PASS }}"
    
